name: Run unit tests

on:
  workflow_dispatch:
    inputs:
      nodejs_version:
        description: 'Node.js versions to build'
        options:
        - '"20","18"'
        - '"20"'
        - '"18"'
        type: choice
        required: true
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs_version: ${{ fromJSON(format('[{0}]', inputs.nodejs_version || '"20","18"')) }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}
      - run: npm run test
