name: Insert Insights client in Node.js rebuild

on:
  workflow_call:
    inputs:
      centos_stream_version:
        description: 'CentOS Stream version to build'
        default: "9"
        type: string
        required: true
      nodejs_version:
        description: 'Node.js version to build'
        default: "20"
        type: string
        required: true
      restore_ccache:
        default: true
        required: true
        type: boolean

jobs:
  build-rpms:
    name: Building RPMs for Node.js ${{ inputs.nodejs_version }} on centos-stream${{ inputs.centos_stream_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: hendrikmuhs/ccache-action@c92f40bee50034e84c763e33b317c77adaa81c92  # v1.2.13
        with:
          key: centos-stream-${{ inputs.centos_stream_version }}-nodejs-${{ inputs.nodejs_version }}-${{ github.base_ref || github.ref_name }}
          restore-keys: |
            centos-stream-${{ inputs.centos_stream_version }}-nodejs-${{ inputs.nodejs_version }}-${{ github.base_ref || github.ref_name }}
          restore: ${{ inputs.restore_ccache }}
          save: ${{ github.event.number == '' }}
      - name: Build container insights-js-client-builder:nodejs-${{ inputs.nodejs_version}}.el${{ inputs.centos_stream_version }}
        run: ./scripts/buildcontainer.sh "${{ inputs.centos_stream_version }}" "${{ inputs.nodejs_version }}"
      - name: Free up enough space for the build
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Rebuild nodejs RPMs
        run: |
          mkdir rpmbuild
          docker run --rm --user $(id -u) -v $(pwd):/insights-js-client:Z -v $(pwd)/rpmbuild:/home/mockbuild/rpmbuild:Z -v $(ccache -k cache_dir):/home/mockbuild/.cache/ccache:Z insights-js-client-builder:nodejs-${{ inputs.nodejs_version}}.el${{ inputs.centos_stream_version }} /insights-js-client/scripts/rebuild.sh "/nodejs*.src.rpm"
      - uses: actions/upload-artifact@v4
        with:
          name: rpms-nodejs${{ inputs.nodejs_version }}.el${{ inputs.centos_stream_version }}
          path: |
            rpmbuild/RPMS/**/nodejs-${{ inputs.nodejs_version }}.*.rpm
            rpmbuild/RPMS/**/nodejs-full-i18n-${{ inputs.nodejs_version }}.*.rpm
            rpmbuild/RPMS/**/npm-*${{ inputs.nodejs_version }}.*.rpm
          retention-days: 7
  test-rpms:
    name: Testing RPMs for Node.js ${{ inputs.nodejs_version }} on centos-stream${{ inputs.centos_stream_version }}
    needs: build-rpms
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream${{ inputs.centos_stream_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Patch for archived CentOS Stream 8
        if: ${{ inputs.centos_stream_version == '8' }}
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - uses: actions/download-artifact@v4
        with:
          name: rpms-nodejs${{ inputs.nodejs_version }}.el${{ inputs.centos_stream_version }}
          path: rpmbuild/RPMS/
      - name: Install nodejs RPMs
        run: dnf install -y rpmbuild/RPMS/**/*.rpm
      - name: Run integration tests
        run: npm run test:integration
